include:
  - docker-compose.observability.yaml
services:
  postgres:
    container_name: nestjs-boilerplate-db
    image: postgres:alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./containers/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    networks:
      - nestjs-boilerplate

  redis:
    container_name: nestjs-boilerplate-redis
    image: redis:alpine
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./containers/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - nestjs-boilerplate

  redis-insight:
    container_name: nestjs-boilerplate-redis-insight
    image: redis/redisinsight:latest
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/data
    ports:
      - ${REDIS_INSIGHT_PORT}:5540
    networks:
      - nestjs-boilerplate

  mailpit:
    image: axllent/mailpit
    restart: always
    container_name: nestjs-boilerplate-mail
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - nestjs-boilerplate

volumes:
  containers:
  redisinsight-data:

networks:
  nestjs-boilerplate:
    driver: bridge
