apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: "Trace: $${__value.raw}"

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: "loki"
        mapTagNamesEnabled: true
        filterByTraceID: true
        query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
        tags:
          - key: "service.name"
            value: "service_name"
      serviceMap:
        datasourceUid: "prometheus"
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: "loki"

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherType: label
          matcherRegex: '"(?:trace_id|traceId)":"([A-Fa-f0-9]{32})"'
          url: $${__value.raw}
          datasourceUid: tempo
          urlDisplayLabel: "Trace: $${__value.raw}"

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040
    jsonData:
      keepCookies: [pyroscope_git_session]

  # - name: Mimir
  #   type: prometheus
  #   access: proxy
  #   uid: mimir
  #   url: http://mimir:9009/prometheus
  #   jsonData:
  #     exemplarTraceIdDestinations:
  #       - datasourceUid: tempo
  #         name: traceID
  #     httpMethod: POST
  #     timeInterval: "2s"
  #
